name: kiosk_app
description: Face Attendance Kiosk - Enhanced with Pixel 6 optimization
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  
  # Network & API
  http: ^1.1.2
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Camera & Image Processing
  camera: ^0.10.5+9
  image: ^4.1.3
  image_picker: ^1.0.7
  
  # Device & System
  device_info_plus: ^10.1.0
  permission_handler: ^11.1.0
  wakelock_plus: ^1.1.4
  
  # State Management
  provider: ^6.1.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  
  # Utils
  intl: ^0.19.0
  path_provider: ^2.1.2
  encrypt: ^5.0.1
  
  # Network Discovery
  network_info_plus: ^5.0.1
  multicast_dns: ^0.3.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
