version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/attendance
    depends_on:
      - db
  admin:
    build: ./admin
    ports:
      - "3000:3000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - admin
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: attendance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../data/backups/database:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
      - "6379:6379"
    volumes:
      - ../data/backups/files:/data
